name: CI - Backend e Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-backend:
    name: Build e Testes do Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/plataforma.mentoria

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Compilar e rodar testes com perfil de testes
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Upload cobertura de testes (JaCoCo)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/plataforma.mentoria/target/site/jacoco/


  build-frontend:
    name: Build do Frontend (Angular)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # você pode ajustar se estiver usando outra versão

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto Angular
        run: npm run build -- --configuration=production
